name: Package and upload .jar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      # Checkout our code
      - name: Checkout code
        uses: actions/checkout@v6

      # Setup correct Java version
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      # Build .jar
      - name: Build .jar
        run: mvn -B clean package -DskipTests

      # Upload .jar
      - name: Upload .jar
        uses: actions/upload-artifact@v4
        with:
          name: packaged-jar
          path: target/*.jar